<font size="5">**Model for Predicting Admixture,Cement & Water Quantity**</font>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model, metrics
import pickle

In [2]:
df_bonus = pd.read_csv('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/datasets/ADMIXTURE_Dataset/OPC53_new.csv')
df_bonus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   CEMENT_TYPE         38 non-null     int64  
 1   ADMIXTURE_TYPE      38 non-null     int64  
 2   ADMIXTURE_QUANTITY  38 non-null     float64
 3   CEMENT_QUANTITY     38 non-null     float64
 4   WATER_QUANTITY      38 non-null     float64
 5   PREDICTED_C/W       38 non-null     float64
dtypes: float64(4), int64(2)
memory usage: 1.9 KB


In [3]:
cols=list(df_bonus.columns)
cols

['CEMENT_TYPE',
 'ADMIXTURE_TYPE',
 'ADMIXTURE_QUANTITY',
 'CEMENT_QUANTITY',
 'WATER_QUANTITY',
 'PREDICTED_C/W']

In [4]:
X = df_bonus.iloc[:, [0,1,5]].values
#X = dataset.iloc[:, [2, 3]].values
# here we define y as a multi output matrix
y = df_bonus.iloc[:, [2,3,4]].values

In [5]:
## train_test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# from keras import backend as K
# def rmse(y_pred, y_true):
#     return K.sqrt(K.mean(K.square(y_pred - y_true)))

In [13]:
from sklearn.linear_model import LinearRegression
Lr_model = LinearRegression()
# fit model
Lr_model.fit(X_train, y_train)

LinearRegression()

In [16]:
y_pred = Lr_model.predict(X_test)
r2 = r2_score(y_test,y_pred)
r2

0.4189713407911022

In [12]:
## finding RMSE for training data
from sklearn.metrics import mean_squared_error,r2_score
from math import sqrt
y_pred = Lr_model.predict(X_train)
mse = mean_squared_error(y_train, y_pred)
rmse = sqrt(mse)
rmse

19.450725725385666

In [11]:
## finding RMSE for test data
from sklearn.metrics import mean_squared_error
from math import sqrt
y_pred = Lr_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = sqrt(mse)
rmse

19.430629986689617

In [12]:
Lr_model.score(X_test,y_test)

0.4189713407911022

In [13]:
filename='linear_regression_model1.sav'
pickle.dump(Lr_model,open(filename,'wb'))

In [14]:
pred = Lr_model.predict([[2,1,0.55662864]])
pred

array([[  1.07070208, 343.85420198, 191.97675297]])

In [15]:
from sklearn.tree import DecisionTreeRegressor
Dt_model = DecisionTreeRegressor()
# fit model
Dt_model.fit(X_train, y_train)

DecisionTreeRegressor()

In [16]:
pred = Dt_model.predict([[3,0,0.5]])
pred

array([[  0., 372., 186.]])

In [17]:
filename='dt_model_admixture_model1.sav'
pickle.dump(Dt_model,open(filename,'wb'))

MODEL2

In [15]:
df_bonus = pd.read_csv('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/datasets/ADMIXTURE_Dataset/PPC-1.csv')
df_bonus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   CEMENT_TYPE         75 non-null     int64  
 1   ADMIXTURE_TYPE      75 non-null     int64  
 2   ADMIXTURE_QUANTITY  75 non-null     float64
 3   CEMENT_QUANTITY     75 non-null     float64
 4   WATER_QUANTITY      75 non-null     float64
 5   PREDICTED_C/W       75 non-null     float64
dtypes: float64(4), int64(2)
memory usage: 3.6 KB


In [16]:
X = df_bonus.iloc[:, [0,1,5]].values
#X = dataset.iloc[:, [2, 3]].values
# here we define y as a multi output matrix
y = df_bonus.iloc[:, [2,3,4]].values

In [17]:
## train_test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# from keras import backend as K
# def rmse(y_pred, y_true):
#     return K.sqrt(K.mean(K.square(y_pred - y_true)))

In [18]:
from sklearn.tree import DecisionTreeRegressor
Dt_model = DecisionTreeRegressor()
# fit model
Dt_model.fit(X_train, y_train)

DecisionTreeRegressor()

In [19]:
pred = Dt_model.predict([[1,0,0.426]])
pred

array([[  0., 340., 150.]])

In [20]:
filename='dt_model_admixture_model2.sav'
pickle.dump(Dt_model,open(filename,'wb'))

MODEL 3

In [21]:
df_bonus = pd.read_csv('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/datasets/ADMIXTURE_Dataset/PSC-2.csv')
df_bonus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   CEMENT_TYPE         7 non-null      int64  
 1   ADMIXTURE_TYPE      7 non-null      int64  
 2   ADMIXTURE_QUANTITY  7 non-null      float64
 3   CEMENT_QUANTITY     7 non-null      float64
 4   WATER_QUANTITY      7 non-null      float64
 5   PREDICTED_C/W       7 non-null      float64
dtypes: float64(4), int64(2)
memory usage: 468.0 bytes


In [22]:
X = df_bonus.iloc[:, [0,1,5]].values
#X = dataset.iloc[:, [2, 3]].values
# here we define y as a multi output matrix
y = df_bonus.iloc[:, [2,3,4]].values

In [23]:
## train_test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# from keras import backend as K
# def rmse(y_pred, y_true):
#     return K.sqrt(K.mean(K.square(y_pred - y_true)))

In [24]:
from sklearn.tree import DecisionTreeRegressor
Dt_model = DecisionTreeRegressor()
# fit model
Dt_model.fit(X_train, y_train)

DecisionTreeRegressor()

In [25]:
pred = Dt_model.predict([[1,0,0.426]])
pred

array([[  3.615, 361.26 , 131.985]])

In [26]:
filename='dt_model_admixture_model3.sav'
pickle.dump(Dt_model,open(filename,'wb'))