<font size="5">**FINAL MODEL**</font>

In [2]:
!pip install PrettyTable

In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model, metrics
import pickle
from prettytable import PrettyTable
from sklearn.metrics import r2_score,mean_squared_error
import math

In [4]:
import pandas as pd
df = pd.read_csv("C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/datasets/mix_proportion _dataset/civil_data_old.csv")

In [5]:
X = df.iloc[:, [0,1,2,5,6,7,8,9,10,11,12,13,14,18,19,20]].values
#X = dataset.iloc[:, [2, 3]].values
# here we define y as a multi output matrix
y = df.iloc[:, [3,4,15,16,17]].values

In [6]:
## train_test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# from keras import backend as K
# def rmse(y_pred, y_true):
#     return K.sqrt(K.mean(K.square(y_pred - y_true)))

In [7]:
fck_user_input = 27.5
cement_type= 3

In [8]:
if fck_user_input>=10 and fck_user_input<20:
     fck = fck_user_input +(1.65 * 3.5)
elif fck_user_input>=20 and fck_user_input<30:
     fck = fck_user_input +(1.65 * 4)
elif fck_user_input>=30 and fck_user_input<65:
     fck = fck_user_input +(1.65 * 5)
elif fck_user_input>=65 and fck_user_input<=80:
     fck = fck_user_input +(1.65 * 6)    

In [9]:
if fck_user_input>=10 and fck_user_input<20:
     fck1 = fck_user_input + 5
elif fck_user_input>=20 and fck_user_input<30:
     fck1 = fck_user_input + 5.5
elif fck_user_input>=30 and fck_user_input<65:
     fck1 = fck_user_input + 6.5
elif fck_user_input>=65:
     fck1 = fck_user_input + 8   

In [10]:
if fck>fck1:
    fck=fck
else:
    fck=fck1

In [11]:
print(fck)

34.1


In [12]:
model1 = pickle.load(open('C:/Users/Stephy/Downloads/model1.sav','rb'))

In [13]:
model2 = pickle.load(open('C:/Users/Stephy/Downloads/model2.sav','rb'))

In [14]:
model3 = pickle.load(open('C:/Users/Stephy/Downloads/model3.sav','rb'))

In [15]:
if cement_type == 4:
    pred=model1.predict([[fck]])
    print("model1")
    print(pred)
elif cement_type == 2 or cement_type == 1:
    pred = model2.predict([[fck]])
    print("model2")
    print(pred)
else:
    pred= model3.predict([[fck]])
    print("model3")
    print(pred)

model3
[[0.53640155]]


C:\Users\Stephy\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [16]:
if cement_type==3:
    ad_mix_model = pickle.load(open('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/models/dt_model_admixture_model1.sav','rb'))
elif cement_type==1:
    ad_mix_model = pickle.load(open('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/models/dt_model_admixture_model2.sav','rb'))
else:
    ad_mix_model = pickle.load(open('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/models/dt_model_admixture_model3.sav','rb'))

In [17]:
table1 = PrettyTable(["Admixture quantity", "Cement Quantity", "Water Quantity"])
water_cement_ratio = pred[0][0]
ADMIXTURE_type =1
grade = 2
x_predict = [[grade,ADMIXTURE_type,water_cement_ratio]]
y_pred = ad_mix_model.predict(x_predict)
for row in y_pred:
    table1.add_row([row[0], row[1], row[2]])
print(table1)

+--------------------+-----------------+----------------+
| Admixture quantity | Cement Quantity | Water Quantity |
+--------------------+-----------------+----------------+
|        1.28        |      320.0      |     144.0      |
+--------------------+-----------------+----------------+


In [18]:
grid_search_model = pickle.load(open('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/models/final_model1.sav','rb'))
dt_model = pickle.load(open('C:/Users/Stephy/Downloads/decision_tree_model1.sav','rb'))
rf_model = pickle.load(open('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/models/mix_proportion models/RF_model.sav','rb'))
xg_model = pickle.load(open('C:/Users/Stephy/Downloads/xboost_model.sav','rb'))
mo = pickle.load(open('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/MOUTPUT_REGRESSOR_CHAIN.sav','rb'))
lass_reg =  pickle.load(open('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/mutioutput_chain/lasso.sav','rb'))
ridge_model =  pickle.load(open('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/mutioutput_chain/ridge1.sav','rb'))
xg_boost =  pickle.load(open('C:/Users/Stephy/Desktop/FINAL_YEAR_PROJECT/mutioutput_chain/xboost_model.sav','rb'))

In [19]:
GRADE = 2
cement_type = 3
cement_quantity = y_pred[0][1]
water_quantity = y_pred[0][2]
ADMIXTURE_type = 1
ADMIXTURE_quantity =  y_pred[0][0]
admixture_sp_gr = 1.08
COARSE = 2.7
FINE =2.6
CEMENT =3.12
COARSE_WA=0.55
FINE_WA=2.78
slump = 100
TARGEtfck = fck
C_W = pred[0][0]

1. KNN WITH GRID SEARCH CROSS VALIDATION

In [20]:
x_new = [[GRADE,cement_type,cement_quantity,water_quantity,fck,ADMIXTURE_type,ADMIXTURE_quantity,admixture_sp_gr,COARSE,FINE,CEMENT,COARSE_WA,FINE_WA,slump,TARGEtfck,C_W]]
y_new_grid = grid_search_model.predict(x_new)

table1 = PrettyTable(["FA","CA","Charecteristic Strength(fck)"])
for row in y_new_grid:
    table1.add_row([row[0], row[1], row[2]])
print(table1)

+------------------+--------------------+------------------------------+
|        FA        |         CA         | Charecteristic Strength(fck) |
+------------------+--------------------+------------------------------+
| 700.876947368421 | 1225.1158947368422 |      34.865263157894745      |
+------------------+--------------------+------------------------------+


In [21]:
y_pred1 = grid_search_model.predict(X_test)
r2 = r2_score(y_test,y_pred1)
r2

-0.035649013540234954

In [22]:
sum = 0
for i in range(len(X_test)):
    sum += abs(y_test[i] - y_pred1[i])
mae = sum/len(X_test)
mae

array([35.01297368, 37.79222807,  3.67688596, 27.07492105, 14.81993684])

In [23]:
mean_squared_error(y_test,y_pred1)

983.4293122003003

In [24]:
mse = np.square(np.subtract(y_test,y_pred1)).mean()
rmse = math.sqrt(mse)
rmse

31.359676532137573

2. RANDOM FOREST PREDICTION

In [25]:
x_new = [[GRADE,cement_type,cement_quantity,water_quantity,fck,ADMIXTURE_type,ADMIXTURE_quantity,admixture_sp_gr,COARSE,FINE,CEMENT,COARSE_WA,FINE_WA,slump,TARGEtfck,C_W]]
y_new_rf = rf_model.predict(x_new)
table1 = PrettyTable(["FA","CA","Charecteristic Strength(fck)"])
for row in y_new_rf:
    table1.add_row([row[0], row[1], row[2]])
print(table1)

+-------------------+--------------------+------------------------------+
|         FA        |         CA         | Charecteristic Strength(fck) |
+-------------------+--------------------+------------------------------+
| 700.3094399999995 | 1242.1844999999992 |      34.786449999999974      |
+-------------------+--------------------+------------------------------+


In [26]:
y_pred2 = rf_model.predict(X_test)
r2 = r2_score(y_test,y_pred2)
r2

0.29579716875366857

In [27]:
mean_squared_error(y_test,y_pred2)

638.4534944760079

In [28]:
mse = np.square(np.subtract(y_test,y_pred2)).mean()
rmse = math.sqrt(mse)
rmse

25.26763729508574

In [29]:
sum = 0
for i in range(len(X_test)):
    sum += abs(y_test[i] - y_pred2[i])
mae = sum/len(X_test)
mae

array([20.07330417, 32.083925  ,  2.84577083, 22.86885762, 14.05234069])

3. LASSO REGRESSION

In [30]:
x_new = [[GRADE,cement_type,cement_quantity,water_quantity,fck,ADMIXTURE_type,ADMIXTURE_quantity,admixture_sp_gr,COARSE,FINE,CEMENT,COARSE_WA,FINE_WA,slump,TARGEtfck,C_W]]
y_new_lasso = lass_reg.predict(x_new)
table1 = PrettyTable(["FA","CA","Charecteristic Strength(fck)"])
for row in y_new_lasso:
    table1.add_row([row[0], row[1], row[2]])
print(table1)

+-------------------+--------------------+------------------------------+
|         FA        |         CA         | Charecteristic Strength(fck) |
+-------------------+--------------------+------------------------------+
| 746.2980370278802 | 1149.6346882766593 |      35.55357019267814       |
+-------------------+--------------------+------------------------------+


In [31]:
y_pred3 = lass_reg.predict(X_test)
r2 = r2_score(y_test,y_pred3)
r2

0.22404453587534454

In [32]:
mean_squared_error(y_test,y_pred3)

707.7050810342901

In [33]:
mse = np.square(np.subtract(y_test,y_pred3)).mean()
rmse = math.sqrt(mse)
rmse

26.602726947331735

In [34]:
sum = 0
for i in range(len(X_test)):
    sum += abs(y_test[i] - y_pred3[i])
mae = sum/len(X_test)
mae

array([28.14053089, 24.31716976,  0.62574248, 22.05844867, 15.70469165])

4. RIDGE REGRESSSION PREDICTION

In [35]:
x_new = [[GRADE,cement_type,cement_quantity,water_quantity,fck,ADMIXTURE_type,ADMIXTURE_quantity,admixture_sp_gr,COARSE,FINE,CEMENT,COARSE_WA,FINE_WA,slump,TARGEtfck,C_W]]
y_new_ridge = ridge_model.predict(x_new)
table1 = PrettyTable(["FA","CA","Charecteristic Strength(fck)"])
for row in y_new_grid:
    table1.add_row([row[0], row[1], row[2]])
print(table1)

+------------------+--------------------+------------------------------+
|        FA        |         CA         | Charecteristic Strength(fck) |
+------------------+--------------------+------------------------------+
| 700.876947368421 | 1225.1158947368422 |      34.865263157894745      |
+------------------+--------------------+------------------------------+


In [36]:
y_pred4 = ridge_model.predict(X_test)
r2 = r2_score(y_test,y_pred4)
r2

0.32988804005040523

In [37]:
mse = np.square(np.subtract(y_test,y_pred4)).mean()
rmse = math.sqrt(mse)
rmse

24.892369817581997

In [38]:
sum = 0
for i in range(len(X_test)):
    sum += abs(y_test[i] - y_pred4[i])
mae = sum/len(X_test)
mae

array([26.65731272, 23.26142502,  0.60800137, 20.16121241, 14.46400806])

5. XGBOOST PREDICTION

In [139]:
x_new = [[GRADE,cement_type,cement_quantity,water_quantity,fck,ADMIXTURE_type,ADMIXTURE_quantity,admixture_sp_gr,COARSE,FINE,CEMENT,COARSE_WA,FINE_WA,slump,TARGEtfck,C_W]]
y_new_boost = xg_boost.predict(x_new)
table1 = PrettyTable(["FA","CA","Charecteristic Strength(fck)"])
for row in y_new_boost:
    table1.add_row([row[0], row[1], row[2]])
print(table1)

+----------+-----------+------------------------------+
|    FA    |     CA    | Charecteristic Strength(fck) |
+----------+-----------+------------------------------+
| 733.5394 | 1180.5951 |          34.144444           |
+----------+-----------+------------------------------+


In [140]:
y_pred5 = xg_boost.predict(X_test)
r2 = r2_score(y_test,y_pred5)
r2

0.9770005318493935

In [141]:
mse = np.square(np.subtract(y_test,y_pred5)).mean()
rmse = math.sqrt(mse)
rmse

4.889680635523921

In [142]:
sum = 0
for i in range(len(X_test)):
    sum += abs(y_test[i] - y_pred5[i])
mae = sum/len(X_test)
mae

array([1.72074504, 3.12774373, 0.15011921, 1.81885136, 2.01411705])

In [149]:
if ADMIXTURE_type == 1:
    carbon_emission1 = y_pred[0][1] * 0.870 + y_pred[0][2] * 0.01 + 0.004 * y_new_grid[0][0] + y_new_grid[0][1] * 0.046 + y_pred[0][0]*0.9 
    carbon_emission2 =y_pred[0][1] * 0.870 + y_pred[0][2] * 0.01 + 0.004 * y_new_rf[0][0] + y_new_rf[0][1] * 0.046 + y_pred[0][0]*0.9 
    carbon_emission3 =y_pred[0][1]  * 0.870 + y_pred[0][2] * 0.01 + 0.004 * y_new_lasso[0][0] + y_new_lasso[0][1] * 0.046 + y_pred[0][0]*0.9 
    carbon_emission4 = y_pred[0][1] * 0.870 + y_pred[0][2] * 0.01 + 0.004 * y_new_ridge[0][0] + y_new_ridge[0][1] * 0.046 + y_pred[0][0]*0.9 
    carbon_emission5 = y_pred[0][1] * 0.870 + y_pred[0][2] * 0.01 + 0.004 * y_new_boost[0][0] + y_new_boost[0][1] * 0.046 + y_pred[0][0]*0.9 
else:
    carbon_emission1 = y_pred[0][1]* 0.870 + y_pred[0][2] * 0.01 +  0.004 * y_new_grid[0][0] + y_new_grid[0][1] * 0.046 + y_pred[0][0]*2.4 
    carbon_emission2 =  y_pred[0][1]* 0.870 + y_pred[0][2] * 0.01 +  0.004 * y_new_rf[0][0] + y_new_rf[0][1] * 0.046 + y_pred[0][0]*2.4
    carbon_emission3 =  y_pred[0][1]* 0.870 + y_pred[0][2] * 0.01 +  0.004 * y_new_lasso[0][0] + y_new_lasso[0][1] * 0.046 + y_pred[0][0]*2.4
    carbon_emission4 = y_pred[0][1]* 0.870 + y_pred[0][2] * 0.01 +  0.004 * y_new_ridge[0][0] + y_new_ridge[0][1] * 0.046 + y_pred[0][0]*2.4
    carbon_emission5 = y_pred[0][1]* 0.870 + y_pred[0][2] * 0.01 +  0.004 * y_new_boost[0][0] + y_new_boost[0][1] * 0.046 + y_pred[0][0]*2.4

In [150]:
print(carbon_emission1)

340.1508389473684


In [151]:
print(carbon_emission2)

340.9337247599999


In [146]:
print(carbon_emission3)

336.86038780883786


In [152]:
print(carbon_emission4)

335.66914330900653


In [153]:
print(carbon_emission5)

338.2335319824219


EVALUATING THE MODELS

In [102]:
## finding RMSE for training data
from sklearn.metrics import mean_squared_error
from math import sqrt
y_pred = grid_search_model.predict(X_train)
mse = mean_squared_error(y_train, y_pred)
rmse = sqrt(mse)
print("RMSE",rmse)
knn_R_squared=grid_search_model.score(X_test,y_test)
print("Measure of deterimination of K-nn model is : ",knn_R_squared)
## finding RMSE for test data
y_pred = grid_search_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = sqrt(mse)
rmse

RMSE 44.245140932687406
Measure of deterimination of K-nn model is :  -0.035649013540234954


31.359676532137577

In [22]:
## finding RMSE for training data
from sklearn.metrics import mean_squared_error
from math import sqrt
y_pred = dt_model.predict(X_train)
mse = mean_squared_error(y_train, y_pred)
rmse = sqrt(mse)
print("RMSE",rmse)
knn_R_squared=dt_model.score(X_test,y_test)
print("Measure of deterimination of DEcision tree model is : ",knn_R_squared)
## finding RMSE for test data
y_pred = dt_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = sqrt(mse)
rmse

RMSE 0.0
Measure of deterimination of DEcision tree model is :  -1.366574428623694


45.213103330063994

In [23]:
## finding RMSE for training data
from sklearn.metrics import mean_squared_error
from math import sqrt
y_pred = rf_model.predict(X_train)
mse = mean_squared_error(y_train, y_pred)
rmse = sqrt(mse)
print("RMSE",rmse)
knn_R_squared=rf_model.score(X_test,y_test)
print("Measure of deterimination of random forest model is : ",knn_R_squared)
## finding RMSE for test data
y_pred = rf_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = sqrt(mse)
rmse

RMSE 12.311565221479368
Measure of deterimination of random forest model is :  -0.07974786057153865


32.99532171785472

In [24]:
## finding RMSE for training data
from sklearn.metrics import mean_squared_error
from math import sqrt
y_pred = xg_model.predict(X_train)
mse = mean_squared_error(y_train, y_pred)
rmse = sqrt(mse)
print("RMSE",rmse)
knn_R_squared=xg_model.score(X_test,y_test)
print("Measure of deterimination of XGBOOST model is : ",knn_R_squared)
## finding RMSE for test data
y_pred = xg_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = sqrt(mse)
rmse

RMSE 0.0009744063651118419
Measure of deterimination of XGBOOST model is :  0.999999940307846


0.0013713448787278566